apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: semics
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: iot-backend
  name: iot-backend
  namespace: semics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iot-backend
    spec:
      containers:
      - image: iot-backend
        name: iot-backend
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: iot-backend
  name: iot-backend
  namespace: semics
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: iot-backend
  type: ClusterIP
status:
  loadBalancer: {}
